//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment_History
    {
        public int EQ_History_ID { get; set; }
        public Nullable<int> Equipment_ID { get; set; }
        public string Serial_Number { get; set; }
        public string EQ_Type { get; set; }
        public string Deployed_To { get; set; }
        public string Status { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Machine_Name { get; set; }
        public string Conway_Tag { get; set; }
        public string Notes { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Field { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        public virtual Equipment Equipment { get; set; }
    }
}
